allenai/scispacy

SciSpaCy/data_util.py
SciSpaCy/per_class_scorer.py
scripts/train_ner.py
tests/fixtures/med_mentions.txt
tests/test_data_util.py
tests/test_per_class_scorer.py

This adds a script which trains a model on the entity mentions from the [MedMentions](https://github.com/chanzuckerberg/MedMentions) dataset (for entity linking). The F1 is around 60 ish if I use the subset of the data which is cleaner (typically used for Information Retrieval research) and constrained to a smaller number of UMLS semantic types. 
I don't actually have any idea of the overall plan for SciSpacy so maybe this isn't super useful (the dataset format is used by some other biomedical NER datasets though, so we could reuse some of this code regardless). I mainly did this because I wanted to play around with the dataset, as it's quite new and looks quite good.

Med mentions

---

Dockerfile
Makefile

Add a Makefile shell to generate the various components. Eventually I want all of these commands to run without having to download any data, by using the `cached_path` function I added and storing all the data we need in an S3 bucket.

add makefile shell to fill in

---

docs/Gemfile
docs/_config.yml
docs/index.md

a github pages shell that we can edit when we are ready.

gh pages shell

---

Makefile
data/meta_large.json
data/meta_small.json
scripts/init_model.py

Adds a custom init model script which creates a vocab and optionally vectors. It also adds a bit of functionality:
- Allows not adding all the words in the vectors file to the vocab (this makes the model massive because the pubmed vectors are very large)
- Allows overriding items in the `meta.json` file so that we can have correct info in our models
- Makes providing the vectors actually optional.

Custom init model

---

Makefile
scispacy/data_util.py
scripts/init_model.py
scripts/train_ner.py
scripts/train_parser_and_tagger.py

- Cleans up some argparsing
- Makes it possible to read the med mentions data from a tar file which is necessary to be able to do things seamlessly with `cached_path`
- adds a couple of makefile commands which build the NER model on top of the parser

Pipeline improvements

---

Makefile
scispacy/file_cache.py
scispacy/per_class_scorer.py
scripts/train_ner.py
scripts/train_parser_and_tagger.py
tests/custom_tests/test_all_model.py
tests/test_per_class_scorer.py

Fixes some stuff from actually trying to train the pipeline:
- Be more careful with the ` with nlp.disable_pipes` because this actually removes the pipes from the model when they are under this scope, meaning some parts of the pipeline don't get serialized
- Fixes embarrassing bug I introduced in the `PerClassScorer` which modified the input
- Adds more words to the large model's vocab, in correlation with Spacy

Build models

---

scripts/init_model.py
scripts/train_ner.py
scripts/train_parser_and_tagger.py
scripts/train_specialised_ner.py

@DeNeutoy are you opposed to adding the sentence segmentation pipe back in? I think its useful for real body text, and as a place for other potential ad hoc fixes

Add sentence segmentation pipe and fix pipeline order

---

scispacy/data_util.py
scripts/linking.py

The goal is to iterate on this baseline until reaching a decent performance before integrating it with spacy. 
This one has the following performance: 
- MedMentions entities not in UMLS: 0
- MedMentions entities found in UMLS: 71062
- Correct linking: 30.19%
- Wrong linking: 3.93%
- No linking: 65.88%

baseline linking model

---

Dockerfile

@ibeltagy this should fix the CI for your PR.

upgrade to stretch

---

README.md
docs/index.md
scispacy/version.py
scripts/release.py

Performance (the performance bump ended up being the same between starting with base and starting with full md, so I went with starting with base for the specialized ner models)
en_core_sci_sm:
- genia UAS: 89.47
- genia LAS: 87.61
- onto UAS: 85.48
- medmentions F1 overall: 0.676
en_core_sci_md:
- genia UAS: 89.94
- genia LAS: 88.08
- onto UAS: 86.70
- medmentions F1 overall: 0.693
en_ner_bc5cdr_md: 0.843
en_ner_bionlp13cg_md: 0.785
en_ner_craft_md: 0.769
en_ner_jnlpba_md: 0.745

Release v0.2.0

---

scripts/linking.py

Currently requires 5GB
Model files are here: `s3://ai2-s2-scispacy/data/linking_model/`
Run the model with this: `python3 scripts/linking.py --medmentions_path data/medmentions --umls_path data/umls_2017_aa_cat0129.json --k 1,2,10,100,1000 --model_path data/linking_model`

Reduce memory usage for linking at prediction time

---

scripts/linking.py

Moves from including each alias per concept to just having a unique set of words, which each have a mapping back to concepts that they are aliases for. Also adds some code around thresholding NN results by similarity.

Deduplicated linking

---

scispacy/abbreviation.py
tests/test_abbreviation_detection.py

I thought this would be generally useful and also specifically might also help the entity linking efforts, because now we'll be able to expand abbreviations which are mentioned in the text, which it pretty common.

add abbreviation detection and tests

---

scripts/linking.py

```
python scripts/linking.py --medmentions_path s3_data/med_mentions --umls_path s3_data/umls_2017_aa_cat0129.json --model_path data/linking_model2/ --ks 80 --thresholds 1.0 --spacy_model en_core_sci_md --use_soft_matching
K: 80, Filtered threshold : 1.0
Gold concept in candidates: 71.60%
Gold concept not in candidates: 17.35%
Doc level gold concept in candidates: 80.65%
Doc level gold concepts missed: 19.35%
Candidate generation failed: 11.05%
Mention linking precision 46.61%
Doc linking precision 42.67%
Normalized doc linking precision 60.04%
Doc linking recall 48.42%
Linking mention-level recall@1: 41.98%
Normalized linking mention-level recall@1: 58.63%
Linking mention-level recall@3: 54.96%
Normalized linking mention-level recall@3: 76.76%
Linking mention-level recall@5: 59.02% …
```

Doc level eval

---

proto_model/__init__.py

remove scispacy dependency for models

---

scispacy/consts.py

Came across a couple abbreviations that were annoying me by breaking sentence splitting.

Add a couple more biological abbreviations

---

scispacy/candidate_generation.py
tests/test_candidate_generation.py

Add empty check to candidate generator

---

data/meta_large.json
scripts/base_model.sh
scripts/ner.sh
scripts/pipeline.sh

Add pipeline stuff for large model.
Also I updated the freq statistics to be calculated based on a 36GB subset of gorc, which is much larger than previously. This required updating the base models to use new minimum word freq stats so as not to be massively large. 
The new models will have:
`en_core_sci_lg`: Vocab = 785k, vectors=600k, 600mb
`en_core_sci_md`: Vocab = 363k, vectors=50k, 96mb
`en_core_sci_sm`: Vocab = 100k, vectors=0k, 12mb

Large model

---

README.md
docs/index.md
scispacy/version.py

Update docs and readme for new release

Release v0.2.3

---

scispacy/abbreviation.py
tests/test_abbreviation_detection.py

Fix abbreviation detection for <short> (<long>) pattern

---

scispacy/abbreviation.py
tests/test_abbreviation_detection.py

Fixes #161 a couple cases are xfailed because i don't see an obvious way to exclude them (i.e. they aren't the result of an obvious bug, but a failure of the algorithm)

Tweak short form filter of abbreviation detector and apply it in both cases

---

requirements.in
setup.py

Hello there,
This addresses #228.

remove awscli dependency, and add request dependency. 

---

scispacy/candidate_generation.py
scispacy/custom_sentence_segmenter.py
scispacy/custom_tokenizer.py
scispacy/linking_utils.py
scispacy/umls_semantic_type_tree.py
tests/custom_tests/test_custom_segmentation.py

A couple of xfail changes. The main code change is to handle pysbd returning spans with spaces included.

Pysbd upgrade

---

README.md
scispacy/hearst_patterns.py
scispacy/hyponym_detector.py
tests/test_hyponym_detector.py

A spacy matcher for hearst patterns, built off of #127 / Steve Anning's work. We need to get approval from him that we can use his converted patterns before we merge this, but it is functional.

Spacy Matcher for hearst patterns

---

scispacy/data_util.py

I know we don't really support windows, just fixing this one since someone opened an issue and it was easy.
Fixes #292

Windows utf8

---

README.md

Updates instructions on using EntityLinker with linkers other than the default.
Fixes #324

Update README on EntityLinker 0.4

---

scispacy/hyponym_detector.py

Fix to a problem described in this issue: https://github.com/allenai/scispacy/issues/339

Hyponym detector index error fix

---

scispacy/candidate_generation.py

Add m parameter documentation

---

project.yml

add --no-sign-request to med_mentions and core assets

Correct a download issue related to s3 auth

---

Dockerfile
README.md
configs/base_ner.cfg
configs/base_ner_scibert.cfg
configs/base_parser_tagger.cfg
configs/base_parser_tagger_scibert.cfg
configs/base_specialized_ner.cfg
docs/index.md
project.yml
requirements.in
scispacy/abbreviation.py
scispacy/hearst_patterns.py
scispacy/version.py
scripts/evaluate_ner.py
setup.py
tests/custom_tests/test_custom_segmentation.py
tests/test_hyponym_detector.py

Spacy 32 upgrade

---

scispacy/candidate_generation.py
scispacy/umls_utils.py

Thanks for the amazing library! 
Hit the following error using export_umls_json.py with UMLS 2022AA:
'charmap' codec can't decode byte 0x81 in position X: character maps to <undefined>
Resolved by adding the utf-8 encoding throughout umls_utils.

encoding="utf-8"

---

.flake8
evaluation/evaluate_linker.py
project.yml
requirements.in
scispacy/abbreviation.py
scispacy/candidate_generation.py
scispacy/data_util.py
scispacy/file_cache.py
scispacy/hyponym_detector.py
scispacy/linking.py
scispacy/linking_utils.py
scispacy/per_class_scorer.py
scispacy/train_utils.py
scispacy/umls_semantic_type_tree.py
scispacy/umls_utils.py
scispacy/version.py
tests/test_abbreviation_detection.py

Update to the latest UMLS version

---

scispacy/candidate_generation.py

1. Updating nmslib hyperparameters guide url.
2. Updating UMLS concept alias path variable with appropriate name.

Updating nmslib hyperparameters guide url 

---

scispacy/version.py

Version bump
