allenai/scispacy

SciSpaCy/umls_semantic_type_tree.py, data/umls_semantic_type_tree.tsv, tests/fixtures/test_umls_tree.tsv, tests/test_umls_semantic_type_tree.py
Adds a UMLS Semantic Type tree. I'm going to use this to collapse the label space of the NER to see if it helps accuracy/F1.
Depth vs num labels:
```
1: 3
2: 7
3: 27
4: 67
5: 91
6: 110
7: 127
```
E.g for depth 3, this is the label space, which looks like a good trade off between granularity and not having a massive number of very similar labels:
```
Behavior
Group Attribute
Group
Natural Phenomenon or Process
Injury or Poisoning
Physical Object
Manufactured Object
Occupation or Discipline
Organization
Finding
UnknownType
Human-caused Phenomenon or Process
Substance
Phenomenon or Process
Event
Activity
ILanguage
Occupational Activity
Entity
Intellectual Product
Organism
Daily or Recreational Activity
Conceptual Entity
Organism Attribute
Idea or Concept
Anatomical Structure
Machine Activity …
```
=> UMLS Semantic Type tree

data/bc5cdr_ner.json, data/bionlp13cg_ner.json, data/craft_ner.json, data/jnlpba_ner.json, data/meta_medium.json, data/meta_small.json, scripts/create_model_package.sh, scripts/pipeline.sh
I discovered that the pip install was broken because it was looking for spacy >= 2.1.0a6. If we are basing off of spacy-nightly, in order for pip install to work (spacy.load with the path to the model directory would still work), the metas need to have a parent_package key set to spacy-nightly.
Also, added check to remove directory if it already exists in pipeline.sh, because it seemed to not be recreating everything if you run pipeline.sh again after a successful build
=> Base packages on spacy-nightly

README.md
Inline type hinting with mypy requires python 3.6
=> Bump required python version to 3.6

scripts/linking.py
Changes:
- Refactored to use a class, as eventually we'll want to maintain some state around the candidate generator.
- refactored `generate_candidates` to return a `List[Dict]` for each mention. The dictionary contains a mapping from `umls_canonical_id -> [list of cosine distances]`. note that the length of this dictionary for each mention may not be `k`, because we are doing NN search on the union of canonical ids and aliases, which will be mapped back to their canonical id.
- use `scipy.sparse.save_npz` and `numpy.float16` during serialisation as well as avoiding serializing arrays with `dtype=numpy.object`, resulting in the tfidf vectors reducing in size from 1.8G to 395MB.
- serialise the concept ids using json, not numpy: 193MB -> 67MB
- Deduplicating the aliases before computing …
=> Linking improvements

scripts/linking.py
Evaluates candidate generation using a spacy model for ner instead of gold mentions. In this setting, an entity candidate is considered correct if that entity is in the gold entities for a given abstract. i.e. candidate entities are evaluated for correctness at the document level instead of the mention level, to avoid the complexity of trying to align mentions produced by the spacy model with the gold mentions.
=> Add an evaluation option to use a spacy model for ner instead of gold mentions

scripts/linking.py
Changes:
1. A spacy model is now required, because we need the doc to do abbreviation dectection, even with gold mentions.
2. Refactored a bit, pulling out some functions
3. Moved the check for generating the training data outside of the main evaluation function so the script fails faster.
4. Refactored to actually use the doc creation function, (additionally pulls out the generation of the gold and predicted mentions, because I need to be able to modify them when replacing abbreviations).
Both results below use gold mentions. 
**Without abbreviations**
Gold concept in candidates: 83.67%
Gold concept not in candidates: 16.29%
Doc level gold concept in candidates: 92.79%
Doc level gold concepts missed: 7.21%
**With abbreviations**
Gold concept in candidates: 86.60%
Gold concept not in …
=> Abbr linker

scispacy/abbreviation.py, scripts/linking.py, tests/test_abbreviation_detection.py
Originally I set up the abbreviation component to return `LongForm, Set[ShortForm]` tuples, which was the wrong way to go about it because mostly, people will want to manipulate the short forms of the abbreviations. This way works much better.
=> Abbreviation api

scispacy/candidate_generation.py
Avoid converting from list to numpy.array and back. Now it takes less than 10GB of memory (down from 200GB)
=> memory efficient candidate generation 

scripts/train_ner.py, scripts/train_parser_and_tagger.py
Fixes #140 
The issue was that we were not disabling the other pipes when we called `nlp.begin_training()` so the parser pipe was getting `begin_training` called on it. It is possible that we don't need to call `begin_training` at all when we are starting from an existing model (see https://github.com/explosion/spaCy/blob/04113a844d9042f04c1fa0bc5830f11355b9b526/spacy/cli/train.py#L208-L213), but this seems to fix the problem.
The results of `spacy evaluate` on genia dev are:
POS       98.62
UAS       89.13
LAS       87.56
and the results of `train_ner --run_test` on med mentions dev are:
precision-untyped:               0.6776682259805685
recall-untyped:                  0.6628886010362695
f1-measure-untyped:              0.6701969409034441
=> disable pipes when creating optimizers

README.md
@lucylw asked me if it was possible to resolve abbreviations prior to performing linking to prevent creating spurious candidates for acronyms. Since this feature already exists, I thought we should document it.
=> Add resolve abbreviations to readme

requirements.in, scispacy/abbreviation.py, setup.py
The current models are not compatible with spacy 2.2. Pinning the scispacy version until we can upgrade to 2.2 and release new models.
=> Pin scispacy to 2.1.x

scispacy/abbreviation.py, tests/test_abbreviation_detection.py
Code crashed if there were parens at the start of the doc, resulting in an empty short/long candidate
=> Abbreviation fix

README.md, docs/index.md, scispacy/version.py
Updates for the release - i'm going to bump to `0.3.0-unreleased` in a separate PR, just in case the new github actions thing to publish to pypi goes wrong and I need to fix it, but normally we would be able to just roll that up into the same PR and choose the commit to tag as the release.
If you could try installing one of the models (I did and it was fine, but just to be sure) that would be great.
=> Release v0.3.0

scispacy/linking_utils.py
line 65 is the only actual change
Before:
After:
Possibly a small change that allows entity linker to run on 16gb machine: #285
=> Change load to generator

Dockerfile
CI is failing because the python/debian combination in the Dockerfile doesn't have a wheel for the latest spacy, so its trying to build it or something. Seems reasonable to update to python 3.8 and latest stable debian anyway.
Should unblock #293
=> update dockerfile python and debian

scispacy/candidate_generation.py, tests/test_candidate_generation.py
The order of candidates returned from the UMLS candidate generator could be different between retries, so that when different candidates have the same scores, entity linker could return different results for each retry because of the `max_entities_per_mention` limit.
This PR is to sort the candidates from the candidate generator, so that the entity linker returns consistent results between retries.
=> Sort the candidates in entity linker.

scispacy/linking.py
This commit updates the docstring to include current supported linkers.
=> Update EntityLinker docstring

scispacy/umls_utils.py, scripts/export_umls_json.py
In relation with Issue #477, here is a modified version of `scispacy/umls_utils.py` we are using to filter UMLS concepts by language. The options are also included as arguments in the .JSON exporter.
=> Support UMLS filtering by language (Solves #477)

README.md
By default the abbreviation detector pipe is not serializable, so you run into issues when you try to serialize any docs processed with it:
```python
from spacy.tokens import DocBin
nlp = spacy.load("en_core_sci_sm")
nlp.add_pipe("abbreviation_detector")
doc_bin = DocBin(store_user_data=True)
doc = nlp("Spinal and bulbar muscular atrophy (SBMA) is an inherited motor neuron disease caused by the expansion of a polyglutamine tract within the androgen receptor (AR). SBMA can be caused by this easily.")
doc_bin.add(doc)
```
It took me a while to figure out this is easily solved with the `make_serializable` parameter, but it's not documented anywhere so I am proposing to add a short note in the readme about it.
=> Add a note about make_serializable argument

scispacy/linking.py
Drop the `umls` and `umls_ents` attributes in the linker that were there for backward compatibility. Closes #488.
=> Drop umls and umls_ents attributes in linker

setup.py
The project URL in the setup.py seems to be outdated. It's updated with the latest URL.
=> Fixes #485 Project Page URL in setup.py

scispacy/file_cache.py
I have discussed with the maintainer in [issue-490](https://github.com/allenai/scispacy/issues/490), and encouraged to raise this PR.
**Gist**:
To use scispacy, some of the resources are fetched from web url, e.g. [URL of tfidf_vectors_sparse](https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/data/linkers/2023-04-23/umls/tfidf_vectors_sparse.npz). And the size of the resources could be up to 500M, thereby taking several miutes to complete downloading. Somehow scispacy download quietly without signals for users, so thet can't tell whether the progress stucks or not.
So I add a progress bar to the function `http_get` to let users know where they are.
Scispacy helps me a lot in my research, thanks for your contribution to our community. And thanks for your review.
=> add progress bar to http_get

scripts/export_umls_json.py
Fixing the previous commit for export_umls_json.py to add non_suppressed into main func call.
=> Fix export_umls_json.py

README.md
Adding to the docs on alternatives to install `mslib`, I thought it would be useful to add the shorter variant
```
pip install "nmslib @ git+https://github.com/nmslib/nmslib.git/#subdirectory=python_bindings"
```
as taken from https://github.com/allenai/scispacy/issues/473#issuecomment-1590443024. Works for me on Windows 10 & Python 3.10.
=> Add shorter version of pip installing nmslib from source

README.md
updated README.md to include installation method of nmslib on Apple M2 chip, using Python3.9, and added an icon for my installation method.
=> update readme to include installation method for nmslib on Apple M2 chip using python3.9

scispacy/linking_utils.py, tests/test_linking.py
This PR refactors the constructor of the `KnowledgeBase` class to extend it in two ways:
1. Enable passing a `Path` object (in addition to a string)
2. Enable passing any iterable (e.g., a list) of `Entity` objects
This will enable making custom KB objects, such as using Wikidata (as requested in https://github.com/allenai/scispacy/issues/346) or using biomedical ontologies (as requested in https://github.com/allenai/scispacy/issues/331)
This PR was originally part of #542, but that PR had too many things going on, so I split out this part to be simpler to review.
Corresponding PR in my fork (for testing purposes, because I can't run CI on the upstream): https://github.com/cthoyt/scispacy/pull/8
=> Refactor KnowledgeBase constructor

README.md
Following these improvements in scispaCy:
- https://github.com/allenai/scispacy/pull/544
- https://github.com/allenai/scispacy/pull/547
- https://github.com/allenai/scispacy/pull/549
- https://github.com/biopragmatics/pyobo/pull/437
This PR adds documentation on to the README to showcase how arbitrary ontologies and databases can be loaded for use as a scispaCy entity linker via PyOBO. It does this by:
1. Adding an end-to-end example for annotating genes using HGNC
2. Adds a link to more example usage in the PyOBO docs at https://pyobo.readthedocs.io/en/latest/scispacy.html
This also closes #331. `hgnc` can be replaced with `to` to use the Plant Trait Ontology, however I wasn't able to construct a convincing use case, so that can be left to the issue submitter.
=> Document extending scispaCy with additional ontologies with PyOBO
